"""initialmigration

Revision ID: f0b9df7fabee
Revises: 
Create Date: 2024-03-21 16:45:10.310676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0b9df7fabee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('companies')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('publication_date',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_constraint('books_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('books_ibfk_2', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('price_unit')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_unit', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('books_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('books_ibfk_1', 'companies', ['company_id'], ['id'])
        batch_op.alter_column('publication_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    op.create_table('companies',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('origin', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='companies_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('company')
    # ### end Alembic commands ###
